:imagesdir: ../../assets/images
include::../style.adoc[]


== Kafka Basics - Topics

A topic is a collection of messages that you want to group together for processing by a consumer. It is a named, append-only stream of records (events/messages). Think of it like a log file you never edit in place — you only append new entries.

=== Why Topics?
They decouple producers (writers) and consumers (readers). Many producers can write, many consumers can read — independently and at their own pace.

=== Key properties

. *Immutable, append-only:* records are never updated in place.

. *Multi-subscriber:* any number of consumers can read the same topic without interfering with each other.

. *Retention-based:* Kafka keeps data based on time (e.g., 7 days) and/or size (e.g., 100GB), not “until consumed”.


=== Records (messages) inside a topic

. *Key (optional):* used for partitioning & compaction semantics.

. *Value:* your payload (JSON, Avro, Protobuf, bytes).

. *Headers (optional):* metadata (trace IDs, content-type, etc.).

. *Timestamp:* event time or broker time.


=== Creating a Topic

. Create a Kafka topic named `demo` with 3 partitions and a replication factor of 1 using the following command.
+
[source,sh,role="execute",subs=attributes+]
----
oc run -n kafka topic-create --rm -it --restart=Never \
  --image=registry.redhat.io/amq-streams/kafka-40-rhel9:3.0.0 -- \
  bash -lc '/opt/kafka/bin/kafka-topics.sh --bootstrap-server my-kafka-kafka-bootstrap:9092 --create --topic demo --partitions 3 --replication-factor 1'
----


. Describe the topic
+
[source,sh,role="execute",subs=attributes+]
----
oc run -n kafka topic-describe --rm -it --restart=Never \
  --image=registry.redhat.io/amq-streams/kafka-40-rhel9:3.0.0 -- \
  bash -lc '/opt/kafka/bin/kafka-topics.sh --bootstrap-server my-kafka-kafka-bootstrap:9092 --describe --topic demo'
----







